#!/usr/bin/env bash

export PADDLE_ENABLE_MKLDNN="${PADDLE_ENABLE_MKLDNN:-0}"
export PADDLE_PDX_DISABLE_MODEL_SOURCE_CHECK="${PADDLE_PDX_DISABLE_MODEL_SOURCE_CHECK:-True}"
export PADDLE_PDX_CACHE_HOME="${PADDLE_PDX_CACHE_HOME:-$HOME/.cache/pdfextractor/paddlex}"

echo "Paddle environment:"
echo "  PADDLE_ENABLE_MKLDNN=$PADDLE_ENABLE_MKLDNN"
echo "  PADDLE_PDX_DISABLE_MODEL_SOURCE_CHECK=$PADDLE_PDX_DISABLE_MODEL_SOURCE_CHECK"
echo "  PADDLE_PDX_CACHE_HOME=$PADDLE_PDX_CACHE_HOME"
